[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "P33"
authors = [{name = "p33", email = "p33.fakeemail.com"}]
dynamic = ["version", "description"]
